/**
 * Anthropic Provider (Claude)
 *
 * AI provider that calls Anthropic's Messages API for text generation tasks.
 * Uses native fetch — no external SDK required.
 */

import {
  BaseAIProvider,
  type AIContext,
  type AIResult,
  type AITaskType,
} from "../ai-provider-contract";

// ─── Types ──────────────────────────────────────────────────────────────────

interface AnthropicMessage {
  role: "user" | "assistant";
  content: string;
}

interface AnthropicResponse {
  id: string;
  type: "message";
  role: "assistant";
  content: Array<{ type: "text"; text: string }>;
  model: string;
  stop_reason: string;
  usage: {
    input_tokens: number;
    output_tokens: number;
  };
}

// ─── Provider ───────────────────────────────────────────────────────────────

export class AnthropicProvider extends BaseAIProvider {
  readonly key = "anthropic";
  readonly name = "Anthropic Claude";
  readonly supportedTasks: AITaskType[] = [
    "summarize",
    "classify",
    "recommend",
    "analyze_sentiment",
    "extract_entities",
    "generate_text",
    "next_best_action",
  ];
  readonly isNative = false;

  private get model(): string {
    return this.config.model ?? "claude-sonnet-4-20250514";
  }

  private get apiKey(): string {
    if (!this.config.apiKey) {
      throw new Error("Anthropic API key not configured");
    }
    return this.config.apiKey;
  }

  private get baseUrl(): string {
    return this.config.baseUrl ?? "https://api.anthropic.com/v1";
  }

  // ── Core API Call ─────────────────────────────────────────────────────

  private async sendMessage(
    systemPrompt: string,
    messages: AnthropicMessage[],
    _taskType: AITaskType
  ): Promise<{ content: string; tokens: { input: number; output: number }; latencyMs: number }> {
    const start = Date.now();

    const response = await fetch(`${this.baseUrl}/messages`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": this.apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: this.model,
        max_tokens: this.config.maxTokens ?? 1024,
        system: systemPrompt,
        messages,
      }),
      signal: this.config.timeout
        ? AbortSignal.timeout(this.config.timeout)
        : undefined,
    });

    if (!response.ok) {
      const errorBody = await response.text().catch(() => "unknown error");
      if (response.status === 429) {
        throw new Error(`Anthropic rate limit exceeded: ${errorBody}`);
      }
      throw new Error(
        `Anthropic API error (${response.status}): ${errorBody}`
      );
    }

    const data = (await response.json()) as AnthropicResponse;
    const content =
      data.content
        ?.filter((block) => block.type === "text")
        .map((block) => block.text)
        .join("") ?? "";

    const latencyMs = Date.now() - start;

    return {
      content,
      tokens: {
        input: data.usage?.input_tokens ?? 0,
        output: data.usage?.output_tokens ?? 0,
      },
      latencyMs,
    };
  }

  private makeResult(
    taskType: AITaskType,
    content: string,
    tokens: { input: number; output: number },
    latencyMs: number,
    structured?: Record<string, unknown>
  ): AIResult {
    return {
      taskType,
      provider: this.key,
      content,
      structured,
      confidence: 0.88,
      reasoning: `Generated by Anthropic ${this.model}`,
      tokens,
      latencyMs,
      cached: false,
    };
  }

  // ── Task Implementations ──────────────────────────────────────────────

  async summarize(content: string, _context?: AIContext): Promise<AIResult> {
    const { content: result, tokens, latencyMs } = await this.sendMessage(
      "You are a concise summarizer for a CRM system. Summarize the following content in 2-3 sentences, focusing on actionable insights.",
      [{ role: "user", content }],
      "summarize"
    );

    return this.makeResult("summarize", result, tokens, latencyMs, {
      summary: result,
    });
  }

  async classify(
    input: string,
    categories: string[],
    _context?: AIContext
  ): Promise<AIResult> {
    const { content: result, tokens, latencyMs } = await this.sendMessage(
      `You are a classifier for a CRM system. Classify the following text into exactly one of these categories: ${categories.join(", ")}. Respond with only the category name.`,
      [{ role: "user", content: input }],
      "classify"
    );

    const category = result.trim();

    return this.makeResult("classify", category, tokens, latencyMs, {
      category,
      allCategories: categories,
    });
  }

  async analyze(context: AIContext): Promise<AIResult> {
    const text = String(
      context.data.text ?? context.data.body ?? context.data.content ?? ""
    );

    const { content: result, tokens, latencyMs } = await this.sendMessage(
      'You are a sentiment analyzer for a CRM system. Analyze the sentiment of the following text. Respond in JSON format: {"sentiment": "positive|negative|neutral", "score": <-1 to 1>, "reasoning": "..."}',
      [{ role: "user", content: text }],
      "analyze_sentiment"
    );

    let structured: Record<string, unknown> = {};
    try {
      structured = JSON.parse(result) as Record<string, unknown>;
    } catch {
      structured = { sentiment: result, raw: result };
    }

    return this.makeResult(
      "analyze_sentiment",
      String(structured.sentiment ?? result),
      tokens,
      latencyMs,
      structured
    );
  }

  async extractEntities(text: string): Promise<AIResult> {
    const { content: result, tokens, latencyMs } = await this.sendMessage(
      'Extract entities from the following text. Return JSON: {"entities": {"people": [], "companies": [], "emails": [], "phones": [], "money": [], "dates": []}}',
      [{ role: "user", content: text }],
      "extract_entities"
    );

    let structured: Record<string, unknown> = {};
    try {
      structured = JSON.parse(result) as Record<string, unknown>;
    } catch {
      structured = { raw: result };
    }

    return this.makeResult(
      "extract_entities",
      result,
      tokens,
      latencyMs,
      structured
    );
  }

  async generateText(
    prompt: string,
    context?: AIContext
  ): Promise<AIResult> {
    const systemPrompt = context
      ? `You are an AI assistant for a CRM system. Context: working with ${context.entityType} (ID: ${context.entityId}).`
      : "You are an AI assistant for a CRM system.";

    const { content: result, tokens, latencyMs } = await this.sendMessage(
      systemPrompt,
      [{ role: "user", content: prompt }],
      "generate_text"
    );

    return this.makeResult("generate_text", result, tokens, latencyMs);
  }

  async recommend(context: AIContext): Promise<AIResult> {
    const { content: result, tokens, latencyMs } = await this.sendMessage(
      'You are a CRM advisor. Based on the entity data provided, suggest the single most impactful next action. Respond in JSON: {"action": "...", "reason": "...", "priority": "HIGH|MEDIUM|LOW"}',
      [
        {
          role: "user",
          content: `Entity type: ${context.entityType}\nData: ${JSON.stringify(context.data)}`,
        },
      ],
      "next_best_action"
    );

    let structured: Record<string, unknown> = {};
    try {
      structured = JSON.parse(result) as Record<string, unknown>;
    } catch {
      structured = { action: result, raw: result };
    }

    return this.makeResult(
      "next_best_action",
      String(structured.action ?? result),
      tokens,
      latencyMs,
      structured
    );
  }

  // ── Healthcheck ───────────────────────────────────────────────────────

  async healthcheck() {
    const start = Date.now();

    try {
      // Anthropic doesn't have a lightweight health endpoint,
      // so we send a minimal request
      const response = await fetch(`${this.baseUrl}/messages`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": this.apiKey,
          "anthropic-version": "2023-06-01",
        },
        body: JSON.stringify({
          model: this.model,
          max_tokens: 1,
          messages: [{ role: "user", content: "hi" }],
        }),
        signal: AbortSignal.timeout(5000),
      });

      return {
        healthy: response.ok,
        message: response.ok
          ? "Anthropic API is reachable"
          : `Anthropic API returned ${response.status}`,
        latencyMs: Date.now() - start,
      };
    } catch (err) {
      return {
        healthy: false,
        message: `Anthropic API unreachable: ${err instanceof Error ? err.message : "unknown error"}`,
        latencyMs: Date.now() - start,
      };
    }
  }

  // ── Cost Estimation ───────────────────────────────────────────────────

  estimateCost(taskType: AITaskType, inputLength: number) {
    // Rough estimates based on Claude Sonnet pricing ($3/1M input, $15/1M output)
    const inputTokens = Math.ceil(inputLength / 4);
    const outputTokens =
      taskType === "generate_text" ? 500 : taskType === "summarize" ? 200 : 100;

    const inputCost = (inputTokens / 1_000_000) * 3;
    const outputCost = (outputTokens / 1_000_000) * 15;

    return {
      estimatedCost: Math.round((inputCost + outputCost) * 10000) / 10000,
      currency: "USD",
    };
  }
}
